language: java
jdk:
  - oraclejdk11
env:
  global:
    - CODECOV_TOKEN="7f78d1c3-b08b-4916-acd9-c2ea3ebc9dc6"
before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
script:
  - ./gradlew test build jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)